services:
  backend:
    build: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src

  frontend:
    build: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend